# Generated by Django 2.2.5 on 2019-09-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190922_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='newborn_tpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilo', models.CharField(max_length=10, verbose_name='kilo')),
                ('hafta', models.CharField(max_length=10, verbose_name='hafta')),
                ('zaman', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
