# Generated by Django 2.2.5 on 2019-09-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_newborn_tpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newborn_tpn',
            name='hafta',
            field=models.IntegerField(max_length=10, verbose_name='hafta'),
        ),
        migrations.AlterField(
            model_name='newborn_tpn',
            name='kilo',
            field=models.IntegerField(max_length=10, verbose_name='kilo'),
        ),
    ]
