# Generated by Django 2.2.5 on 2019-09-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190923_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newborn_tpn',
            name='hafta',
            field=models.IntegerField(verbose_name='Hafta (gh)'),
        ),
    ]
