# Generated by Django 2.2.5 on 2019-09-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190924_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='newborn_tpn',
            name='lipit',
            field=models.IntegerField(default=1, verbose_name='Lipit (gr)'),
            preserve_default=False,
        ),
    ]
