# Generated by Django 2.2.5 on 2019-09-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_newborn_tpn_lipit'),
    ]

    operations = [
        migrations.AddField(
            model_name='newborn_tpn',
            name='maturite',
            field=models.CharField(choices=[('pm', 'prematur'), ('matur', 'matur')], default='matur', max_length=2),
        ),
    ]
