# Generated by Django 2.2.5 on 2019-09-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_newborn_tpn_maturite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newborn_tpn',
            name='maturite',
            field=models.CharField(choices=[('pm', 'prematur'), ('matur', 'matur')], default='matur', max_length=5),
        ),
    ]
