# Generated by Django 2.2.5 on 2019-09-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20190925_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newborn_tpn',
            name='hafta',
        ),
    ]
