# Generated by Django 2.2.5 on 2019-09-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_remove_newborn_tpn_hafta'),
    ]

    operations = [
        migrations.AddField(
            model_name='newborn_tpn',
            name='hafta',
            field=models.IntegerField(default=1, verbose_name='Hafta (gh)'),
            preserve_default=False,
        ),
    ]
