# Generated by Django 2.2.5 on 2019-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_newborn_tpn_hafta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ped_ix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilo', models.FloatField(verbose_name='Kilo (kg)')),
                ('total_mayi', models.CharField(choices=[('cc', 'cc_kg'), ('m2', 'm2')], default='cc', max_length=2)),
                ('total', models.IntegerField(verbose_name='Totali kaçtan')),
                ('sodyum', models.FloatField(verbose_name='Sodyum (meq)')),
                ('potasyum', models.FloatField(verbose_name='Potasyum (meq)')),
                ('kalsiyum', models.FloatField(verbose_name='Calsiyum (meq)')),
                ('glukoz', models.FloatField(verbose_name='Glukoz (gr)')),
                ('zaman', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
