# Generated by Django 2.2.5 on 2019-09-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_ped_ix'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ped_ix',
            new_name='ped_mix',
        ),
    ]
