# Generated by Django 2.2.5 on 2019-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20190925_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newborn_tpn',
            name='aminoasit',
            field=models.FloatField(verbose_name='Aminoasit (gr)'),
        ),
        migrations.AlterField(
            model_name='newborn_tpn',
            name='glukoz',
            field=models.FloatField(verbose_name='Glukoz (gr)'),
        ),
        migrations.AlterField(
            model_name='newborn_tpn',
            name='kalsiyum',
            field=models.FloatField(verbose_name='Calsiyum (meq)'),
        ),
        migrations.AlterField(
            model_name='newborn_tpn',
            name='lipit',
            field=models.FloatField(verbose_name='Lipit (gr)'),
        ),
        migrations.AlterField(
            model_name='newborn_tpn',
            name='potasyum',
            field=models.FloatField(verbose_name='Potasyum (meq)'),
        ),
        migrations.AlterField(
            model_name='newborn_tpn',
            name='sodyum',
            field=models.FloatField(verbose_name='Sodyum (meq)'),
        ),
    ]
